language: python
python: "3.7"
dist: xenial

env:
  - >
    LOCUST_MIN_WAIT=30
    LOCUST_MAX_WAIT=90
    MATOMO_SITE_ID=1
    MATOMO_SITE_BASE_URL=http://example.com/
    MATOMO_TRACKER_SUBPATH=matomo.php

cache:
  pip: true

install:
  - pip install --upgrade pip
  - pip install poetry codecov
  - poetry install -v

script:
  - ./.hooks/pre-commit
  - flake8
  - pytest --cov -s

after_success:
  - codecov

before_deploy:
  - mkdir -p ./build/
  - export ARTIFACT_VERSION="`echo $TRAVIS_TAG | sed 's/^v//'`"
  - >
    git archive HEAD
    -o ./build/tracking-load-faker-${ARTIFACT_VERSION}.tar.gz
    --prefix=tracking-load-faker/

deploy:
  api_key: "${GITHUB_TOKEN}"
  provider: releases
  file_glob: true
  file: ./build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
