language: python
python: "3.7"
dist: xenial

addons:
  apt:
    sources:
      - sourceline: ppa:duggan/bats
    packages:
      - bats
      - bc

env:
  - >
    LOCUST_MIN_WAIT=30
    LOCUST_MAX_WAIT=90
    MATOMO_SITE_ID=1
    MATOMO_SITE_BASE_URL=http://example.com/
    MATOMO_TRACKER_SUBPATH=matomo.php

cache:
  pip: true

before_install:
  - pip install --upgrade pip
  - pip install poetry codecov

install:
  - poetry install -v

test:
  - ./.deploy/lint.sh
  - ./.deploy/check-requirements.sh
  - ./.deploy/test.sh

after_success:
  - codecov

before_deploy:
  - mkdir -p ./build/
  - export ARTIFACT_VERSION="`echo $TRAVIS_TAG | sed 's/^v//'`"
  - >
    git archive HEAD
    -o ./build/tracking-load-faker-${ARTIFACT_VERSION}.tar.gz
    --prefix=tracking-load-faker/

deploy:
  api_key: "${GITHUB_TOKEN}"
  provider: releases
  file_glob: true
  file: ./build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
