ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app
RUN \
  apk add --no-cache --virtual .build-deps \
    g++=8.3.0-r0 \
    libffi-dev=3.2.1-r6 \
    openssl-dev=1.1.1d-r2 \
    python3-dev=3.7.5-r1 \
  && pip install -r requirements.txt \
  && apk del --purge .build-deps
